# Generated by Django 5.0.3 on 2024-03-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student1_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student1',
            new_name='Student',
        ),
    ]
