# Generated by Django 5.0.3 on 2024-03-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_student1_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student1',
        ),
    ]
