# Generated by Django 5.0.3 on 2024-03-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_student_student1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student1',
            old_name='Firstname',
            new_name='Fullname',
        ),
        migrations.RemoveField(
            model_name='student1',
            name='Lastname',
        ),
    ]
